# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    utilisateur.service:
        class: Gedi\BaseBundle\Services\UtilisateurService
        arguments: [ "@doctrine.orm.entity_manager", "@security.encoder_factory" ]

    groupe.service:
        class: Gedi\BaseBundle\Services\GroupeService
        arguments: [ "@doctrine.orm.entity_manager" ]

    projet.service:
        class: Gedi\BaseBundle\Services\ProjetService
        arguments: [ "@doctrine.orm.entity_manager" ]

    document.service:
        class: Gedi\BaseBundle\Services\DocumentService
        arguments: [ "@doctrine.orm.entity_manager" ]

    fichier.service:
        class: edi\BaseBundle\Services\FichierService
        arguments: ['%fichiers_directory%']