home_user:
    path:     /home_user
    defaults: { _controller: GediUserBundle:User:home }

account_user:
    path:     /account_user
    defaults: { _controller: GediUserBundle:User:account }

recent_user:
    path:     /recent_user
    defaults: { _controller: GediUserBundle:User:recent }

shared_user:
    path:     /shared_user
    defaults: { _controller: GediUserBundle:User:shared }